<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Volcano;
use Illuminate\Support\Facades\DB;

class VolcanoesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    /**
     * 
     * === GET THE MISSING FILES TO RUN THE LARAVEL APP WITH COMPOSER ===
     * 
     *  1. composer install
     *  2. cp .env.example .env
     *  3. php artisan key:generate
     *  4. php artisan migrate
     */

    public function run(): void
    {
        // Clear existing volcanoes
        DB::table('volcanoes')->truncate();
        
        // ⚠️ Remember, to refresh the data you must: "php artisan migrate:fresh --seed"

        // Add real volcano data
        $volcanoes = [
            [
                'name' => 'Abu',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Inactive', // Active, Inactive, Extinct
                'latitude' => 34.50,
                'longitude' => 131.60,
                'elevation' => 641,
                'description' => 'A group of shield volcanoes located on the southwest end of Honshu Island, with the highest peak being Irao-yama.',
                'type' => 'Shield',
                'image_url' => 'abu'
            ],
            [
                'name' => 'Acamarachi',
                'country' => 'Chile',
                'continent' => 'South America',
                'activity' => 'Extinct',
                'latitude' => -23.30,
                'longitude' => -67.62,
                'elevation' => 6046,
                'description' => 'A steep, cone-shaped stratovolcano in the Andes, with evidence of postglacial lava flows and an Incan sanctuary.',
                'type' => 'Stratovolcano',
                'image_url' => 'acamarachi'
            ],
            [
                'name' => 'Acatenango',
                'country' => 'Guatemala',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 14.50,
                'longitude' => -90.88,
                'elevation' => 3976,
                'description' => 'A prominent stratovolcano near Antigua, Guatemala, with a history of explosive eruptions and significant pyroclastic flows.',
                'type' => 'Stratovolcano',
                'image_url' => 'acatenango'
            ],
            [
                'name' => 'Acıgöl-Nevşehir',
                'country' => 'Turkey',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 38.537,
                'longitude' => 34.621,
                'elevation' => 1683,
                'description' => 'A late Pleistocene caldera (~7 × 8 km), with post-caldera maars, lava domes, pyroclastic cones.',
                'type' => 'Caldera',
                'image_url' => 'acigöl-nevsehir'
            ],
            [
                'name' => 'Mount Adams',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 46.21,
                'longitude' => -121.49,
                'elevation' => 3742,
                'description' => 'A large stratovolcano in the Cascades. Last significant eruptions are in the geologic past (~ thousands to tens of thousands of years ago).',
                'type' => 'Stratovolcano',
                'image_url' => 'adams'
            ],
            [
                'name' => 'Adams Seamount',
                'country' => 'Pacific Ocean',
                'continent' => 'International Waters',
                'activity' => 'Active',
                'latitude' => -25.37,
                'longitude' => -129.27,
                'elevation' => -39,
                'description' => 'A submarine volcano rising ~3,500 m above the seafloor to within ~39 m of the surface. No confirmed historic eruptions in very recent times, but geologic data indicates relatively recent activity.',
                'type' => 'Submarine volcano',
                'image_url' => 'adams-seamount'
            ],
            [
                'name' => 'Adatara',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 37.64,
                'longitude' => 140.29,
                'elevation' => 1728,
                'description' => 'A complex of overlapping stratovolcanoes east of Bandai volcano. The latest eruptions are from the Numano-daira crater. (volcano.si.edu)',
                'type' => 'Stratovolcano',
                'image_url' => 'adatara'
            ],
            [
                'name' => 'Adwa',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Inactive',
                'latitude' => 10.07,
                'longitude' => 40.84,
                'elevation' => 1733,
                'description' => 'A stratovolcano with a 4 × 5 km caldera, young basaltic flows, and fumarolic activity. Uncertain historical eruptions possibly in 1828 or 1928.',
                'type' => 'Stratovolcano',
                'image_url' => 'adwa'
            ],
            [
                'name' => 'Afderà',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Inactive',
                'latitude' => 13.08,
                'longitude' => 40.85,
                'elevation' => 1295,
                'description' => 'An isolated rhyolitic stratovolcano located at the intersection of three fault systems between the Erta Ale, Tat Ali, and Alayta mountain ranges in the Danakil Depression.',
                'type' => 'Stratovolcano',
                'image_url' => 'afdera'
            ],
            [
                'name' => 'Agrigan',
                'country' => 'Mariana Islands',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 18.77,
                'longitude' => 145.67,
                'elevation' => 965,
                'description' => 'The highest of the Marianas arc volcanoes, containing a 500-meter-deep flat-floored caldera. The elliptical island is 8 km long and its summit is the top of a massive 4000-meter-high submarine volcano. Last eruption was in 1917.',
                'type' => 'Stratovolcano',
                'image_url' => 'agrigan'
            ],
            [
                'name' => 'Agua',
                'country' => 'Guatemala',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 14.47,
                'longitude' => -90.74,
                'elevation' => 3760,
                'description' => 'A symmetrical, forested stratovolcano that forms a prominent backdrop to Antigua Guatemala. Despite its youthful profile, it has had no historical eruptions but produced a devastating mudflow in 1541 that destroyed the first Guatemalan capital.',
                'type' => 'Stratovolcano',
                'image_url' => 'agua'
            ],
            [
                'name' => 'Agua de Pau',
                'country' => 'Portugal',
                'continent' => 'Europe',
                'activity' => 'Inactive',
                'latitude' => 37.77,
                'longitude' => -25.47,
                'elevation' => 947,
                'description' => 'A stratovolcanic complex located in the central part of São Miguel Island in the Azores, recognized for the Lagoa do Fogo caldera lake at its center. Last erupted in 1563-1564.',
                'type' => 'Stratovolcano',
                'image_url' => 'agua_de_pau'
            ],
            [
                'name' => 'Aguilera',
                'country' => 'Chile',
                'continent' => 'South America',
                'activity' => 'Inactive',
                'latitude' => -50.33,
                'longitude' => -73.75,
                'elevation' => 2546,
                'description' => 'A remote stratovolcano located in southern Chilean Patagonia, within the Southern Patagonian Ice Field. It is one of the most isolated volcanoes in the region.',
                'type' => 'Stratovolcano',
                'image_url' => 'aguilera'
            ],
            [
                'name' => 'Agung',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -8.34,
                'longitude' => 115.51,
                'elevation' => 3142,
                'description' => 'A sacred mountain in Bali and the highest point on the island. After 53 years of quiescence, it awoke in 2017 with intense seismicity and erupted in November 2017, continuing with smaller eruptions through 2019.',
                'type' => 'Stratovolcano',
                'image_url' => 'agung'
            ],
            [
                'name' => 'Ahyi',
                'country' => 'Mariana Islands',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 20.42,
                'longitude' => 145.03,
                'elevation' => -137,
                'description' => 'A large conical submarine volcano that rises to within 79 meters of the sea surface, located about 18 km southeast of Farallon de Pajaros. Experienced eruptions in 2001, 2014, and recent unrest in 2024-2025.',
                'type' => 'Submarine',
                'image_url' => 'ahyi'
            ],
            [
                'name' => 'Akademia Nauk',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 53.98,
                'longitude' => 159.45,
                'elevation' => 1180,
                'description' => 'A caldera volcano located on the Kamchatka Peninsula in the eastern part of Russia. Part of the volcanically active Pacific Ring of Fire region.',
                'type' => 'Caldera',
                'image_url' => 'akademia_nauk'
            ],
            [
                'name' => 'Akagi',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 36.56,
                'longitude' => 139.20,
                'elevation' => 1828,
                'description' => 'A stratovolcano located in Gunma Prefecture on Honshu Island, featuring a caldera lake called Lake Onuma. The volcano is considered dormant with no historical eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'akagi'
            ],
            [
                'name' => 'Akan',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 43.38,
                'longitude' => 144.01,
                'elevation' => 1499,
                'description' => 'A caldera volcano in eastern Hokkaido with multiple crater lakes including Lake Akan. The volcanic complex includes several active vents and has experienced numerous small eruptions in recent history.',
                'type' => 'Caldera',
                'image_url' => 'akan'
            ],
            [
                'name' => 'Akhtang',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 55.43,
                'longitude' => 158.65,
                'elevation' => 1956,
                'description' => 'A shield volcano located on the Kamchatka Peninsula in eastern Russia. Part of the Kamchatka volcanic region with no recorded historical eruptions.',
                'type' => 'Shield',
                'image_url' => 'akhtang'
            ],
            //from here GS
            [
                'name' => 'Akita Komagatake',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 39.76,
                'longitude' => 140.8,
                'elevation' => 1637,
                'description' => 'An active stratovolcano in northern Honshu known for periodic phreatic eruptions and scenic crater lakes.',
                'type' => 'Stratovolcano',
                'image_url' => 'akita-komagatake'
            ],
            [
                'name' => 'Akita Yakeyama',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 39.96,
                'longitude' => 140.76,
                'elevation' => 1366,
                'description' => 'A small active stratovolcano in northern Honshu that occasionally emits steam and minor ash.',
                'type' => 'Stratovolcano',
                'image_url' => 'akita-yakeyama'
            ],
            [
                'name' => 'Akusekijima',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 29.46,
                'longitude' => 129.6,
                'elevation' => 584,
                'description' => 'A volcanic island in the Tokara Islands with a steep stratovolcanic cone and occasional fumarolic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'akusekijima'
            ],
            [
                'name' => 'Akutan',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 54.13,
                'longitude' => -165.99,
                'elevation' => 1303,
                'description' => 'An active stratovolcano in the Aleutian Islands frequently producing small eruptions and lava flows.',
                'type' => 'Stratovolcano',
                'image_url' => 'akutan'
            ],
            [
                'name' => 'Alaid',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 50.86,
                'longitude' => 155.55,
                'elevation' => 2339,
                'description' => 'The tallest volcano of the Kuril Islands, Alaid is an active symmetrical stratovolcano known for summit eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'alaid'
            ],
            [
                'name' => 'Alamagan',
                'country' => 'Mariana Islands',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 17.6,
                'longitude' => 145.83,
                'elevation' => 744,
                'description' => 'An active stratovolcano in the northern Marianas featuring a large summit crater and geothermal vents.',
                'type' => 'Stratovolcano',
                'image_url' => 'alamagan'
            ],
            [
                'name' => 'Alayta',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 12.88,
                'longitude' => 40.57,
                'elevation' => 1501,
                'description' => 'A broad shield volcano in the Afar Depression known for extensive basaltic lava flows.',
                'type' => 'Shield',
                'image_url' => 'alayta'
            ],
            [
                'name' => 'Alban Hills',
                'country' => 'Italy',
                'continent' => 'Europe',
                'activity' => 'Inactive',
                'latitude' => 41.73,
                'longitude' => 12.7,
                'elevation' => 949,
                'description' => 'A caldera complex southeast of Rome that last erupted thousands of years ago but shows signs of unrest.',
                'type' => 'Caldera',
                'image_url' => 'alban-hills'
            ],
            [
                'name' => 'Alcedo',
                'country' => 'Galápagos Islands',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -0.43,
                'longitude' => -91.12,
                'elevation' => 1130,
                'description' => 'A large shield volcano on Isabela Island featuring a wide caldera and frequent geothermal activity.',
                'type' => 'Shield',
                'image_url' => 'alcedo'
            ],
            [
                'name' => 'Ale Bagu',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 13.52,
                'longitude' => 40.63,
                'elevation' => 1031,
                'description' => 'An active stratovolcano in the Erta Ale Range showing recent lava flows and fumarolic fields.',
                'type' => 'Stratovolcano',
                'image_url' => 'ale-bagu'
            ],
            [
                'name' => 'Alid',
                'country' => 'Eritrea',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 14.88,
                'longitude' => 39.92,
                'elevation' => 904,
                'description' => 'A stratovolcano in the Danakil Depression showing strong geothermal and fumarolic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'alid'
            ],
            [
                'name' => 'Ambrym',
                'country' => 'Vanuatu',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -16.25,
                'longitude' => 168.12,
                'elevation' => 1334,
                'description' => 'A large volcanic island featuring one of the world’s most active lava lakes within its caldera.',
                'type' => 'Caldera, Shield',
                'image_url' => 'ambrym'
            ],
            [
                'name' => 'Anatahan',
                'country' => 'Mariana Islands',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 16.35,
                'longitude' => 145.67,
                'elevation' => 790,
                'description' => 'An active stratovolcano that erupted violently in 2003 after centuries of dormancy.',
                'type' => 'Stratovolcano',
                'image_url' => 'anatahan'
            ],
            [
                'name' => 'Aneityum',
                'country' => 'Vanuatu',
                'continent' => 'Asia',
                'activity' => 'Extinct',
                'latitude' => -20.2,
                'longitude' => 169.78,
                'elevation' => 852,
                'description' => 'An extinct stratovolcano forming the southernmost island of Vanuatu.',
                'type' => 'Stratovolcano',
                'image_url' => 'aneityum'
            ],
            [
                'name' => 'Aniakchak',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 56.88,
                'longitude' => -158.17,
                'elevation' => 1341,
                'description' => 'A massive caldera in Alaska with evidence of Holocene eruptions and ongoing geothermal activity.',
                'type' => 'Caldera',
                'image_url' => 'aniakchak'
            ],
            [
                'name' => 'Antisana',
                'country' => 'Ecuador',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -0.48,
                'longitude' => -78.14,
                'elevation' => 5753,
                'description' => 'A glaciated active stratovolcano in the Andes east of Quito, known for its steep summit cone.',
                'type' => 'Stratovolcano',
                'image_url' => 'antisana'
            ],
            [
                'name' => 'Aoba',
                'country' => 'Vanuatu',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -15.4,
                'longitude' => 167.83,
                'elevation' => 1496,
                'description' => 'Also known as Ambae, this large shield volcano has erupted frequently with explosive activity and lava flows.',
                'type' => 'Shield',
                'image_url' => 'aoba'
            ],
            [
                'name' => 'Ararat',
                'country' => 'Turkey',
                'continent' => 'Asia',
                'activity' => 'Extinct',
                'latitude' => 39.7,
                'longitude' => 44.3,
                'elevation' => 5165,
                'description' => 'A towering extinct stratovolcano and the highest peak in Turkey, associated with biblical tradition.',
                'type' => 'Stratovolcano',
                'image_url' => 'ararat'
            ],
            [
                'name' => 'Arenal',
                'country' => 'Costa Rica',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 10.46,
                'longitude' => -84.7,
                'elevation' => 1670,
                'description' => 'One of Costa Rica’s most active volcanoes, famous for frequent eruptions between 1968 and 2010.',
                'type' => 'Stratovolcano',
                'image_url' => 'arenal'
            ],
            [
                'name' => 'Arintica',
                'country' => 'Chile',
                'continent' => 'South America',
                'activity' => 'Inactive',
                'latitude' => -18.73,
                'longitude' => -69.05,
                'elevation' => 5597,
                'description' => 'A large andesitic volcanic complex in northern Chile showing no recent eruptive activity.',
                'type' => 'Complex',
                'image_url' => 'arintica'
            ],
            [
                'name' => 'Asacha',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 52.36,
                'longitude' => 157.83,
                'elevation' => 1910,
                'description' => 'A stratovolcano in southern Kamchatka known for recent eruptions and vigorous fumarolic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'asacha'
            ],
            [
                'name' => 'Asama',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 36.4,
                'longitude' => 138.53,
                'elevation' => 2568,
                'description' => 'One of Japan’s most active volcanoes, producing frequent explosive eruptions and ash emissions.',
                'type' => 'Complex',
                'image_url' => 'asama'
            ],
            [
                'name' => 'Ascensión',
                'country' => 'South Atlantic Ocean',
                'continent' => 'International Waters',
                'activity' => 'Inactive',
                'latitude' => -7.95,
                'longitude' => -14.37,
                'elevation' => 858,
                'description' => 'A volcanic island in the South Atlantic formed by a dormant stratovolcano with numerous lava domes.',
                'type' => 'Stratovolcano',
                'image_url' => 'ascension'
            ],
            [
                'name' => 'Askja',
                'country' => 'Iceland',
                'continent' => 'Europe',
                'activity' => 'Active',
                'latitude' => 65.03,
                'longitude' => -16.75,
                'elevation' => 1516,
                'description' => 'An active volcano in central Iceland with a large caldera and a crater lake known as Öskjuvatn.',
                'type' => 'Stratovolcano',
                'image_url' => 'askja'
            ],
            [
                'name' => 'Aso',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 32.88,
                'longitude' => 131.11,
                'elevation' => 1592,
                'description' => 'One of the world’s largest calderas, Aso contains multiple active vents and frequent ash eruptions.',
                'type' => 'Caldera',
                'image_url' => 'aso'
            ],
            [
                'name' => 'Atitlán',
                'country' => 'Guatemala',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 14.58,
                'longitude' => -91.19,
                'elevation' => 3535,
                'description' => 'A picturesque but active volcano overlooking Lake Atitlán, last erupting in the 19th century.',
                'type' => 'Complex',
                'image_url' => 'atitlan'
            ],
            [
                'name' => 'Atka',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 52.38,
                'longitude' => -174.15,
                'elevation' => 1533,
                'description' => 'A large volcanic complex in the Aleutian Islands with several active vents and lava domes.',
                'type' => 'Caldera',
                'image_url' => 'atka'
            ],
            [
                'name' => 'Atsonupuri',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 44.81,
                'longitude' => 147.14,
                'elevation' => 1206,
                'description' => 'A symmetrical stratovolcano on Iturup Island with a central crater and geothermal activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'atsonupuri'
            ],
            [
                'name' => 'Augustine',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 59.36,
                'longitude' => -153.43,
                'elevation' => 1252,
                'description' => 'A frequently active lava dome volcano in Alaska known for explosive eruptions and pyroclastic flows.',
                'type' => 'Lava dome',
                'image_url' => 'augustine'
            ],
            [
                'name' => 'Avachinsky',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 53.26,
                'longitude' => 158.83,
                'elevation' => 2741,
                'description' => 'A prominent Kamchatka stratovolcano near Petropavlovsk that erupts frequently with ash plumes.',
                'type' => 'Stratovolcano',
                'image_url' => 'avachinsky'
            ],
            [
                'name' => 'Awu',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 3.67,
                'longitude' => 125.5,
                'elevation' => 1320,
                'description' => 'A frequently active stratovolcano in the Sangihe Islands known for explosive summit eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'awu'
            ],
            [
                'name' => 'Axial Seamount',
                'country' => 'Pacific Ocean',
                'continent' => 'International Waters',
                'activity' => 'Active',
                'latitude' => 45.95,
                'longitude' => -130.0,
                'elevation' => -1410,
                'description' => 'A submarine volcano on the Juan de Fuca Ridge, one of the most active undersea volcanoes on Earth.',
                'type' => 'Submarine',
                'image_url' => 'axial-seamount'
            ],
            [
                'name' => 'Ayelu',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 10.08,
                'longitude' => 40.7,
                'elevation' => 2145,
                'description' => 'An active stratovolcano in the Afar region showing fumarolic activity and geothermal vents.',
                'type' => 'Stratovolcano',
                'image_url' => 'ayelu'
            ],
            [
                'name' => 'Azufre',
                'country' => 'Chile',
                'continent' => 'South America',
                'activity' => 'Inactive',
                'latitude' => -21.79,
                'longitude' => -68.24,
                'elevation' => 5846,
                'description' => 'A large volcanic complex in the Andes composed of overlapping lava domes and cones.',
                'type' => 'Complex',
                'image_url' => 'azufre'
            ],
            [
                'name' => 'Azuma',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 37.73,
                'longitude' => 140.25,
                'elevation' => 2035,
                'description' => 'An active volcanic group in northern Honshu known for fumaroles and occasional phreatic eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'azuma'
            ],
            [
                'name' => 'Babuyon Claro',
                'country' => 'Philippines',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 19.5,
                'longitude' => 121.9,
                'elevation' => 1180,
                'description' => 'A potentially active stratovolcano on Babuyan Island with geothermal and seismic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'babuyon-claro'
            ],
            [
                'name' => 'Bachelor',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 43.8,
                'longitude' => 121.6,
                'elevation' => 2763,
                'description' => 'An extinct stratovolcano in the Cascade Range of Oregon, now a popular ski destination.',
                'type' => 'Stratovolcano',
                'image_url' => 'bachelor'
            ],
            [
                'name' => 'Bagana',
                'country' => 'Papua New Guinea',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -6.1,
                'longitude' => 155.2,
                'elevation' => 1750,
                'description' => 'One of the most active volcanoes in Papua New Guinea, producing frequent lava flows and ash plumes.',
                'type' => 'Cinder Cone',
                'image_url' => 'bagana'
            ],
            [
                'name' => 'Baker',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 48.79,
                'longitude' => -121.82,
                'elevation' => 3285,
                'description' => 'A glaciated stratovolcano in Washington State showing fumarolic activity and potential for future eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'baker'
            ],
            [
                'name' => 'Bam',
                'country' => 'Papua New Guinea',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -3.6,
                'longitude' => 144.85,
                'elevation' => 685,
                'description' => 'A small active volcanic island off northern Papua New Guinea known for explosive eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'bam'
            ],
            [
                'name' => 'Bamus',
                'country' => 'Papua New Guinea',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -5.2,
                'longitude' => 151.2,
                'elevation' => 2248,
                'description' => 'A forested stratovolcano near Ulawun showing fumarolic activity and signs of recent unrest.',
                'type' => 'Stratovolcano',
                'image_url' => 'bamus'
            ],
            [
                'name' => 'Bandai',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 37.6,
                'longitude' => 140.1,
                'elevation' => 1819,
                'description' => 'A stratovolcano in northern Honshu famous for its 1888 eruption that caused a massive landslide.',
                'type' => 'Stratovolcano',
                'image_url' => 'bandai'
            ],
            [
                'name' => 'Barren Island',
                'country' => 'India',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 12.29,
                'longitude' => 93.88,
                'elevation' => 305,
                'description' => 'India’s only active volcano, located in the Andaman Sea with frequent strombolian eruptions.',
                'type' => 'Pyroclastic cone',
                'image_url' => 'barren-island'
            ],
            [
                'name' => 'Barrier',
                'country' => 'Kenya',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 2.32,
                'longitude' => 36.57,
                'elevation' => 1032,
                'description' => 'A large volcanic complex in the Gregory Rift showing recent lava flows and geothermal activity.',
                'type' => 'Complex',
                'image_url' => 'barrier'
            ],
            [
                'name' => 'Bazman',
                'country' => 'Iran',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 28.0,
                'longitude' => 60.0,
                'elevation' => 3490,
                'description' => 'A dormant stratovolcano in southeastern Iran with a well-preserved cone and summit crater.',
                'type' => 'Stratovolcano',
                'image_url' => 'bazman'
            ],
            [
                'name' => 'Beerenberg',
                'country' => 'Norway',
                'continent' => 'Europe',
                'activity' => 'Active',
                'latitude' => 71.1,
                'longitude' => -8.2,
                'elevation' => 2277,
                'description' => 'The world’s northernmost active volcano, forming Jan Mayen Island in the Arctic Ocean.',
                'type' => 'Stratovolcano',
                'image_url' => 'beerenberg'
            ],
            [
                'name' => 'Belknap',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 44.28,
                'longitude' => -121.83,
                'elevation' => 2096,
                'description' => 'An extinct shield volcano in Oregon’s Cascade Range covered by young basaltic lava flows.',
                'type' => 'Shield',
                'image_url' => 'belknap'
            ],
            [
                'name' => 'Bezymianny',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 55.98,
                'longitude' => 160.58,
                'elevation' => 2882,
                'description' => 'A highly active stratovolcano in Kamchatka known for dome-building eruptions since 1956.',
                'type' => 'Stratovolcano',
                'image_url' => 'bezymianny'
            ],
            [
                'name' => 'Biliran',
                'country' => 'Philippines',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 11.5,
                'longitude' => 124.5,
                'elevation' => 1187,
                'description' => 'A volcanic complex in the central Philippines with geothermal fields and historic eruptions.',
                'type' => 'Complex',
                'image_url' => 'biliran'
            ],
            [
                'name' => 'Bolshoi Semiachik',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 54.32,
                'longitude' => 160.02,
                'elevation' => 1720,
                'description' => 'A large multi-vent stratovolcano in Kamchatka featuring hot springs and hydrothermal fields.',
                'type' => 'Stratovolcano',
                'image_url' => 'bolshoi-semiachik'
            ],
            [
                'name' => 'Bulusan',
                'country' => 'Philippines',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 12.8,
                'longitude' => 124.1,
                'elevation' => 1565,
                'description' => 'An active stratovolcano in southern Luzon known for frequent ash explosions and steam-driven eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'bulusan'
            ],
            [
                'name' => 'Butajira',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Extinct',
                'latitude' => 8.05,
                'longitude' => 38.35,
                'elevation' => 2281,
                'description' => 'A volcanic field with fissure vents and maars in central Ethiopia, now considered extinct.',
                'type' => 'Fissure vent, Maar',
                'image_url' => 'butajira'
            ],
            [
                'name' => 'Cameroon (Mount)',
                'country' => 'Cameroon',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 4.2,
                'longitude' => 9.17,
                'elevation' => 4095,
                'description' => 'West Africa’s highest peak, Mount Cameroon is an active stratovolcano with recent eruptions near the coast.',
                'type' => 'Stratovolcano',
                'image_url' => 'cameroon-mount'
            ],
            [
                'name' => 'Camiguin de Babuyanes',
                'country' => 'Philippines',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 18.83,
                'longitude' => 121.85,
                'elevation' => 712,
                'description' => 'A potentially active stratovolcano north of Luzon showing geothermal and seismic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'camiguin-de-babuyanes'
            ],
            [
                'name' => 'Canlaon',
                'country' => 'Philippines',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 10.41,
                'longitude' => 123.13,
                'elevation' => 2435,
                'description' => 'The highest volcano in the central Philippines, Canlaon frequently emits ash and steam.',
                'type' => 'Stratovolcano',
                'image_url' => 'canlaon'
            ],
            [
                'name' => 'Capulin',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 36.45,
                'longitude' => -104.09,
                'elevation' => 2494,
                'description' => 'An extinct cinder cone in New Mexico, preserved as a classic example of volcanic cone morphology.',
                'type' => 'Cinder Cone',
                'image_url' => 'capulin'
            ],
            [
                'name' => 'Carrizozo',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 33.7,
                'longitude' => -106.0,
                'elevation' => 1730,
                'description' => 'A volcanic field in New Mexico featuring young basaltic lava flows from Holocene eruptions.',
                'type' => 'Volcanic field',
                'image_url' => 'carrizozo'
            ],
            [
                'name' => 'Cayambe',
                'country' => 'Ecuador',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => 0.03,
                'longitude' => -77.99,
                'elevation' => 5790,
                'description' => 'A glaciated stratovolcano near the equator that last erupted in the late 18th century.',
                'type' => 'Stratovolcano',
                'image_url' => 'cayambe'
            ],
            [
                'name' => 'Cereme',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -6.9,
                'longitude' => 108.41,
                'elevation' => 3078,
                'description' => 'Also known as Mount Ciremai, this active stratovolcano in West Java occasionally emits ash and gas.',
                'type' => 'Stratovolcano',
                'image_url' => 'cereme'
            ],
            [
                'name' => 'Chaine des Puys',
                'country' => 'France',
                'continent' => 'Europe',
                'activity' => 'Extinct',
                'latitude' => 45.78,
                'longitude' => 2.97,
                'elevation' => 1464,
                'description' => 'A volcanic field of cinder cones and domes in central France, inactive for over 7,000 years.',
                'type' => 'Lava dome',
                'image_url' => 'chaine-des-puys'
            ],
            [
                'name' => 'Chiginagak',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 57.13,
                'longitude' => -156.99,
                'elevation' => 2067,
                'description' => 'An active stratovolcano in Alaska with recent hydrothermal activity and crater lake overflow events.',
                'type' => 'Stratovolcano',
                'image_url' => 'chiginagak'
            ],
            [
                'name' => 'Chikurachki',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 50.33,
                'longitude' => 155.46,
                'elevation' => 5958,
                'description' => 'The highest volcano of Paramushir Island in the Kurils, frequently emitting ash plumes and lava flows.',
                'type' => 'Stratovolcano',
                'image_url' => 'chikurachki'
            ],
            [
                'name' => 'Chimborazo',
                'country' => 'Ecuador',
                'continent' => 'South America',
                'activity' => 'Extinct',
                'latitude' => -1.46,
                'longitude' => -78.82,
                'elevation' => 6310,
                'description' => 'An extinct stratovolcano and Ecuador’s highest peak, notable as the point on Earth farthest from the planet’s center.',
                'type' => 'Stratovolcano',
                'image_url' => 'chimborazo'
            ],
            [
                'name' => 'Cleveland',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 52.83,
                'longitude' => -169.95,
                'elevation' => 1730,
                'description' => 'One of the Aleutians’ most active volcanoes, Cleveland produces frequent explosive eruptions and ash plumes.',
                'type' => 'Stratovolcano',
                'image_url' => 'cleveland'
            ],
            [
                'name' => 'Coatepeque',
                'country' => 'El Salvador',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 13.86,
                'longitude' => -89.54,
                'elevation' => 746,
                'description' => 'A large caldera in western El Salvador filled by Lake Coatepeque, formed by ancient explosive eruptions.',
                'type' => 'Caldera',
                'image_url' => 'coatepeque'
            ],
            [
                'name' => 'Colima',
                'country' => 'Mexico',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 19.51,
                'longitude' => 103.62,
                'elevation' => 4100,
                'description' => 'One of Mexico’s most active volcanoes, frequently erupting with lava domes and ash explosions.',
                'type' => 'Stratovolcano',
                'image_url' => 'colima'
            ],
            [
                'name' => 'Columbia River Flood Basalts',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 46.5,
                'longitude' => 110.67,
                'elevation' => 0,
                'description' => 'A vast region of ancient basaltic lava flows covering parts of Washington, Oregon, and Idaho.',
                'type' => 'Flood Basalt',
                'image_url' => 'columbia-river-flood-basalts'
            ],
            [
                'name' => 'Concepción',
                'country' => 'Nicaragua',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 11.5,
                'longitude' => 85.6,
                'elevation' => 1610,
                'description' => 'An active stratovolcano forming part of Ometepe Island in Lake Nicaragua with frequent ash eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'concepcion'
            ],
            [
                'name' => 'Copahue',
                'country' => 'Argentina',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -37.85,
                'longitude' => -71.17,
                'elevation' => 2965,
                'description' => 'An active stratovolcano on the Chile-Argentina border known for sulfuric gas emissions and minor eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'copahue'
            ],
            [
                'name' => 'Cosigüina',
                'country' => 'Nicaragua',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 12.98,
                'longitude' => -87.56,
                'elevation' => 847,
                'description' => 'A shield volcano in western Nicaragua whose 1835 eruption was among the largest in Central America’s history.',
                'type' => 'Shield',
                'image_url' => 'cosiguina'
            ],
            [
                'name' => 'Cotopaxi',
                'country' => 'Ecuador',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -0.68,
                'longitude' => -78.44,
                'elevation' => 5911,
                'description' => 'One of the world’s highest active volcanoes, Cotopaxi features a symmetrical cone and frequent eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'cotopaxi'
            ],
            [
                'name' => 'Crater Lake',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 42.94,
                'longitude' => -122.11,
                'elevation' => 2471,
                'description' => 'A massive caldera in Oregon formed by the collapse of Mount Mazama, now filled by deep blue Crater Lake.',
                'type' => 'Caldera',
                'image_url' => 'crater-lake'
            ],
            [
                'name' => 'Craters of the Moon',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 43.42,
                'longitude' => -113.5,
                'elevation' => 2005,
                'description' => 'A vast volcanic field in Idaho featuring young basaltic lava flows and spatter cones.',
                'type' => 'Volcanic field',
                'image_url' => 'craters-of-the-moon'
            ],
            [
                'name' => 'Daisetsu',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 43.7,
                'longitude' => 142.9,
                'elevation' => 2290,
                'description' => 'A volcanic group in central Hokkaido with active fumaroles and geothermal features in Daisetsuzan National Park.',
                'type' => 'Stratovolcano',
                'image_url' => 'daisetsu'
            ],
            [
                'name' => 'Dakataua',
                'country' => 'Papua New Guinea',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -5.0,
                'longitude' => 150.1,
                'elevation' => 400,
                'description' => 'A flooded caldera on the Willaumez Peninsula with signs of recent volcanic unrest and thermal activity.',
                'type' => 'Caldera',
                'image_url' => 'dakataua'
            ],
            [
                'name' => 'Damavand',
                'country' => 'Iran',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 35.95,
                'longitude' => 52.11,
                'elevation' => 5670,
                'description' => 'The highest peak in Iran and the Middle East, showing fumarolic activity near its summit crater.',
                'type' => 'Stratovolcano',
                'image_url' => 'damavand'
            ],
            [
                'name' => 'Deccan Traps',
                'country' => 'India',
                'continent' => 'Asia',
                'activity' => 'Extinct',
                'latitude' => 20.5,
                'longitude' => 73.5,
                'elevation' => 600,
                'description' => 'A massive flood basalt province in western India formed by extensive volcanic eruptions 66 million years ago.',
                'type' => 'Flood Basalt',
                'image_url' => 'deccan-traps'
            ],
            [
                'name' => 'Dempo',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -4.0,
                'longitude' => 103.1,
                'elevation' => 3173,
                'description' => 'An active stratovolcano in southern Sumatra with a crater lake and periodic explosive eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'dempo'
            ],
            [
                'name' => 'Devils Garden',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 43.5,
                'longitude' => -120.9,
                'elevation' => 1525,
                'description' => 'A volcanic field in central Oregon featuring basaltic lava flows and lava tubes formed thousands of years ago.',
                'type' => 'Volcanic field',
                'image_url' => 'devils-garden'
            ],
            [
                'name' => 'Devils Tower',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 44.6,
                'longitude' => -104.7,
                'elevation' => 1558,
                'description' => 'An iconic volcanic plug in Wyoming composed of columnar phonolite, now a national monument.',
                'type' => 'Plug',
                'image_url' => 'devils-tower'
            ],
            [
                'name' => 'Diamond Craters',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 43.1,
                'longitude' => -118.7,
                'elevation' => 1450,
                'description' => 'An extinct volcanic field in southeastern Oregon featuring maars, lava flows, and cinder cones.',
                'type' => 'Volcanic field',
                'image_url' => 'diamond-craters'
            ],
            [
                'name' => 'Dieng Volcanic Complex',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -7.2,
                'longitude' => 109.9,
                'elevation' => 2565,
                'description' => 'A group of active craters and fumaroles in central Java known for hydrothermal activity and toxic gas emissions.',
                'type' => 'Complex',
                'image_url' => 'dieng-volcanic-complex'
            ],
            [
                'name' => 'Diky Greben',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Inactive',
                'latitude' => 51.46,
                'longitude' => 156.98,
                'elevation' => 1331,
                'description' => 'A group of lava domes on the Kamchatka Peninsula showing weak fumarolic activity.',
                'type' => 'Lava dome',
                'image_url' => 'diky-greben'
            ],
            [
                'name' => 'Dubbi',
                'country' => 'Eritrea',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 13.6,
                'longitude' => 41.8,
                'elevation' => 1625,
                'description' => 'An active stratovolcano in the Danakil region that last erupted in 1861, producing large lava flows.',
                'type' => 'Stratovolcano',
                'image_url' => 'dubbi'
            ],
            [
                'name' => 'Dukono',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 1.7,
                'longitude' => 127.87,
                'elevation' => 1185,
                'description' => 'A persistently active volcano on Halmahera producing continuous ash emissions and explosions.',
                'type' => 'Complex',
                'image_url' => 'dukono'
            ],
            [
                'name' => 'East Epi',
                'country' => 'Vanuatu',
                'continent' => 'Oceania',
                'activity' => 'Active',
                'latitude' => -16.7,
                'longitude' => 168.4,
                'elevation' => -34,
                'description' => 'A submarine caldera off Epi Island with frequent shallow eruptions and hydrothermal activity.',
                'type' => 'Caldera',
                'image_url' => 'east-epi'
            ],
            [
                'name' => 'Ebeko',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 50.68,
                'longitude' => 156.02,
                'elevation' => 1156,
                'description' => 'A somma volcano on Paramushir Island known for frequent explosive ash eruptions and gas plumes.',
                'type' => 'Somma',
                'image_url' => 'ebeko'
            ],
            [
                'name' => 'Egmont (Taranaki)',
                'country' => 'New Zealand',
                'continent' => 'Oceania',
                'activity' => 'Active',
                'latitude' => -39.3,
                'longitude' => 174.1,
                'elevation' => 2518,
                'description' => 'A symmetrical stratovolcano on New Zealand’s North Island with a history of moderate eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'egmont-taranaki'
            ],
            [
                'name' => 'Egon',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -8.7,
                'longitude' => 122.45,
                'elevation' => 788,
                'description' => 'An active volcano on Flores Island with a crater lake and frequent small explosive eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'egon'
            ],
            [
                'name' => 'El Chichón',
                'country' => 'Mexico',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 17.36,
                'longitude' => -93.23,
                'elevation' => 1060,
                'description' => 'A caldera volcano in southern Mexico that erupted catastrophically in 1982 after centuries of dormancy.',
                'type' => 'Caldera',
                'image_url' => 'el-chichon'
            ],
            [
                'name' => 'Elbrus',
                'country' => 'Russia',
                'continent' => 'Europe',
                'activity' => 'Inactive',
                'latitude' => 43.33,
                'longitude' => 42.45,
                'elevation' => 5633,
                'description' => 'Europe’s highest peak and a dormant stratovolcano in the Caucasus Mountains with no eruptions in recorded history.',
                'type' => 'Stratovolcano',
                'image_url' => 'elbrus'
            ],
            [
                'name' => 'Erebus',
                'country' => 'Antarctica',
                'continent' => 'Australia',
                'activity' => 'Active',
                'latitude' => -77.5,
                'longitude' => 167.2,
                'elevation' => 3794,
                'description' => 'The world’s southernmost active volcano, Erebus features a persistent lava lake on Ross Island.',
                'type' => 'Stratovolcano',
                'image_url' => 'erebus'
            ],
            [
                'name' => 'Erta Ale',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 13.6,
                'longitude' => 40.7,
                'elevation' => 613,
                'description' => 'A low shield volcano in the Danakil Depression known for its long-lived lava lake and continuous activity.',
                'type' => 'Shield',
                'image_url' => 'erta-ale'
            ],
            [
                'name' => 'Etna',
                'country' => 'Italy',
                'continent' => 'Europe',
                'activity' => 'Active',
                'latitude' => 37.73,
                'longitude' => 15.0,
                'elevation' => 3350,
                'description' => 'Europe’s most active volcano, Etna frequently erupts with lava flows and ash emissions near Catania, Sicily.',
                'type' => 'Stratovolcano',
                'image_url' => 'etna'
            ],
            [
                'name' => 'Fantale',
                'country' => 'Ethiopia',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 8.98,
                'longitude' => 39.93,
                'elevation' => 2007,
                'description' => 'A caldera volcano in the Ethiopian Rift Valley with fumaroles and recent geothermal activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'fantale'
            ],
            [
                'name' => 'Fernandina',
                'country' => 'Ecuador',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -0.37,
                'longitude' => -91.55,
                'elevation' => 1476,
                'description' => 'The most active volcano in the Galápagos Islands, Fernandina regularly produces basaltic lava flows.',
                'type' => 'Caldera',
                'image_url' => 'fernandina'
            ],
            [
                'name' => 'Fisher',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => -54.63,
                'longitude' => -164.42,
                'elevation' => 1095,
                'description' => 'An eroded stratovolcano in the Aleutian Islands showing no signs of recent volcanic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'fisher'
            ],
            [
                'name' => 'Fogo',
                'country' => 'Cape Verde Islands',
                'continent' => 'Africa',
                'activity' => 'Active',
                'latitude' => 14.95,
                'longitude' => -24.35,
                'elevation' => 2829,
                'description' => 'An active volcano dominating Fogo Island, last erupting in 2014 with significant lava flows.',
                'type' => 'Stratovolcano',
                'image_url' => 'fogo'
            ],
            [
                'name' => 'Fort Rock',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Extinct',
                'latitude' => 43.37,
                'longitude' => -121.07,
                'elevation' => 1716,
                'description' => 'A tuff ring in central Oregon formed by a phreatomagmatic eruption through an ancient lakebed.',
                'type' => 'Maar',
                'image_url' => 'fort-rock'
            ],
            [
                'name' => 'Frosty Peak',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 55.08,
                'longitude' => -162.81,
                'elevation' => 1920,
                'description' => 'A glaciated stratovolcano in Alaska’s Aleutian Range showing no known Holocene eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'frosty-peak'
            ],
            [
                'name' => 'Fuego',
                'country' => 'Guatemala',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 14.47,
                'longitude' => -90.88,
                'elevation' => 3763,
                'description' => 'One of Central America’s most active volcanoes, Fuego produces frequent explosive eruptions and ash plumes.',
                'type' => 'Stratovolcano',
                'image_url' => 'fuego'
            ],
            [
                'name' => 'Fuerteventura',
                'country' => 'Spain',
                'continent' => 'Europe',
                'activity' => 'Extinct',
                'latitude' => 28.36,
                'longitude' => -14.02,
                'elevation' => 529,
                'description' => 'An ancient volcanic island in the Canary Islands, now eroded with no recent eruptive activity.',
                'type' => 'Fissure vent',
                'image_url' => 'fuerteventura'
            ],
            [
                'name' => 'Fuji',
                'country' => 'Japan',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 35.36,
                'longitude' => 138.73,
                'elevation' => 3776,
                'description' => 'Japan’s highest and most iconic volcano, Fuji last erupted in 1707 and remains potentially active.',
                'type' => 'Stratovolcano',
                'image_url' => 'fuji'
            ],
            [
                'name' => 'Furnas',
                'country' => 'Portugal',
                'continent' => 'Europe',
                'activity' => 'Active',
                'latitude' => 37.76,
                'longitude' => -25.33,
                'elevation' => 805,
                'description' => 'A caldera volcano on São Miguel Island in the Azores with geothermal vents and historical eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'furnas'
            ],
            [
                'name' => 'Fuss Peak',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 50.27,
                'longitude' => 155.25,
                'elevation' => 1772,
                'description' => 'A steep stratovolcano on Paramushir Island in the Kurils, last known to erupt in the 19th century.',
                'type' => 'Stratovolcano',
                'image_url' => 'fuss-peak'
            ],
            [
                'name' => 'Galeras',
                'country' => 'Colombia',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => 1.22,
                'longitude' => -77.37,
                'elevation' => 4276,
                'description' => 'A frequently active volcano near Pasto, Colombia, known for explosive eruptions and fumarolic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'galeras'
            ],
            [
                'name' => 'Galunggung',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -7.26,
                'longitude' => 108.08,
                'elevation' => 2168,
                'description' => 'A stratovolcano in West Java that last erupted in 1984, producing significant ash and lahars.',
                'type' => 'Stratovolcano',
                'image_url' => 'galunggung'
            ],
            [
                'name' => 'Gamalama',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 0.81,
                'longitude' => 127.33,
                'elevation' => 1715,
                'description' => 'A highly active volcano on Ternate Island with frequent explosive eruptions and ashfall events.',
                'type' => 'Stratovolcano',
                'image_url' => 'gamalama'
            ],
            [
                'name' => 'Gamchen',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 54.97,
                'longitude' => 160.68,
                'elevation' => 2576,
                'description' => 'A large complex stratovolcano in Kamchatka composed of several overlapping cones and craters.',
                'type' => 'Stratovolcano',
                'image_url' => 'gamchen'
            ],
            [
                'name' => 'Gamkonora',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 1.38,
                'longitude' => 127.53,
                'elevation' => 1635,
                'description' => 'An active volcano on Halmahera Island with a large summit crater and frequent eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'gamkonora'
            ],
            [
                'name' => 'Gareloi',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 51.8,
                'longitude' => 178.8,
                'elevation' => 1573,
                'description' => 'An active Aleutian stratovolcano known for frequent ash plumes and explosive eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'gareloi'
            ],
            [
                'name' => 'Gaua',
                'country' => 'Vanuatu',
                'continent' => 'Oceania',
                'activity' => 'Active',
                'latitude' => -14.27,
                'longitude' => 167.5,
                'elevation' => 797,
                'description' => 'A volcanic island with an active caldera lake that frequently emits steam and gas.',
                'type' => 'Stratovolcano',
                'image_url' => 'gaua'
            ],
            [
                'name' => 'Gede',
                'country' => 'Indonesia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => -6.77,
                'longitude' => 106.94,
                'elevation' => 2958,
                'description' => 'A twin-peaked volcano near Jakarta with fumaroles and a history of moderate eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'gede'
            ],
            [
                'name' => 'Glacier Peak',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 48.11,
                'longitude' => -121.11,
                'elevation' => 3213,
                'description' => 'A glaciated stratovolcano in Washington with past large explosive eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'glacier-peak'
            ],
            [
                'name' => 'Gorely',
                'country' => 'Russia',
                'continent' => 'Asia',
                'activity' => 'Active',
                'latitude' => 52.56,
                'longitude' => 158.03,
                'elevation' => 1829,
                'description' => 'A caldera volcano in Kamchatka featuring multiple craters and frequent small eruptions.',
                'type' => 'Caldera',
                'image_url' => 'gorely'
            ],
            [
                'name' => 'Graciosa',
                'country' => 'Portugal',
                'continent' => 'Europe',
                'activity' => 'Inactive',
                'latitude' => 39.02,
                'longitude' => -27.97,
                'elevation' => 402,
                'description' => 'A volcanic island in the Azores with a central caldera and geothermal springs.',
                'type' => 'Stratovolcano',
                'image_url' => 'graciosa'
            ],
            [
                'name' => 'Gran Canaria',
                'country' => 'Spain',
                'continent' => 'Europe',
                'activity' => 'Extinct',
                'latitude' => 28.0,
                'longitude' => 15.58,
                'elevation' => 1950,
                'description' => 'An ancient shield volcano in the Canary Islands shaped by massive eruptions millions of years ago.',
                'type' => 'Fissure vent',
                'image_url' => 'gran-canaria'
            ],
            [
                'name' => 'Great Sitkin',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 52.07,
                'longitude' => -176.13,
                'elevation' => 1740,
                'description' => 'A frequently active Aleutian volcano with lava dome growth and ash emissions.',
                'type' => 'Stratovolcano',
                'image_url' => 'great-sitkin'
            ],
            [
                'name' => 'Griggs',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Inactive',
                'latitude' => 58.35,
                'longitude' => -155.09,
                'elevation' => 2317,
                'description' => 'A large stratovolcano in Katmai National Park showing no recent eruptive activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'griggs'
            ],
            [
                'name' => 'Grímsvötn',
                'country' => 'Iceland',
                'continent' => 'Europe',
                'activity' => 'Active',
                'latitude' => 64.42,
                'longitude' => -17.33,
                'elevation' => 1725,
                'description' => 'Iceland’s most active volcano, erupting beneath the Vatnajökull ice cap and producing jökulhlaups.',
                'type' => 'Caldera',
                'image_url' => 'grimsvotn'
            ],
            [
                'name' => 'Guagua Pichincha',
                'country' => 'Ecuador',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -0.17,
                'longitude' => -78.6,
                'elevation' => 4784,
                'description' => 'A frequently active volcano overlooking Quito, known for ash eruptions and fumarolic activity.',
                'type' => 'Stratovolcano',
                'image_url' => 'guagua-pichincha'
            ],
            [
                'name' => 'Guallatiri',
                'country' => 'Chile',
                'continent' => 'South America',
                'activity' => 'Active',
                'latitude' => -18.42,
                'longitude' => -69.09,
                'elevation' => 6071,
                'description' => 'A high Andean volcano emitting constant fumaroles and occasional explosive eruptions.',
                'type' => 'Stratovolcano',
                'image_url' => 'guallatiri'
            ],
            [
                'name' => 'Guguan',
                'country' => 'United States',
                'continent' => 'North America',
                'activity' => 'Active',
                'latitude' => 17.31,
                'longitude' => 145.84,
                'elevation' => 287,
                'description' => 'A small volcanic island in the Northern Marianas that last erupted in the early 20th century.',
                'type' => 'Stratovolcano',
                'image_url' => 'guguan'
            ],           
];
        
        foreach ($volcanoes as $volcano) {
            Volcano::create($volcano);
        }
    }
}
